name: "Schema Sync Checks"
description: "Check if schema versions are updated"

inputs:
  github-token:
    description: The GitHub token used to create an authenticated client
    default: ${{ github.token }}
    required: false
  ksp-repo:
    description: "Repository of Kafka-secure-proxy"
    required: false
    default: dayvsonmercon/schema-validation-test
  topics-file-path:
    description: "Path of application-topics.yml in Project"
    required: false
    default: kafka-secure-proxy/application-topics.yml

runs:
  using: 'node20'
  main: 'index.js'